version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ims_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - ims
    depends_on:
      - mysql
      - redis
    expose:
      - 9000

  nginx:
    image: nginx:alpine
    container_name: ims_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - ims

  mysql:
    image: mysql:8.0
    container_name: ims_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invoice_system
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ims

  redis:
    image: redis:alpine
    container_name: ims_redis
    ports:
      - "6379:6379"
    networks:
      - ims

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ims_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - ims

volumes:
  db_data:

networks:
  ims:
    driver: bridge
